### ISSUE TITLE
Still active the project ?

### ISSUE THREAD

**Issue by ScriptVortexDE** [LJPc-solutions/freescout-whmcs-module#1]
Hello, I wanted to ask whether the project is still being actively promoted or not. 

I have installed it on my Freescout instance and also provided all data regarding the API of WHMCS but it doesn't seem to work.

It can't connect for whatever reason, at least that's what Freescout tells me. 

But when I look at WHMCS I see that it has tried to log in but, unfortunately, I'm at a loss and wanted to ask you for help.

**Comment by Lars-** [comment]
It is not promoted in any way, but it is active. We’ve built this for one of our customers that is using this every day, so it does work. Maybe the account that you are using doesn’t have API access?

**Comment by ScriptVortexDE** [comment]
Ah okay,

I have created an account that has API access, and also an API key plus token for the account

**Comment by Lars-** [comment]
Did you also give the IP of your freescout permission to use the API? Anyway, you should test your API credentials first (via the server you host freescout at). If that works, but the module still does not work, let me know. 

Some information about the WHMCS API: https://developers.whmcs.com/api/getting-started/

**Comment by ScriptVortexDE** [comment]
WHMCS and Freescout run on the same server with the same IP; if I write my VPN into the API allow list and call the URL it works 

Only from Freescout to WHMCS it doesn't, and I ask myself: Why is that?

**Comment by Lars-** [comment]
Okay, so the module works. Good to know, it is definitely something with your network.

**Comment by ScriptVortexDE** [comment]
No it not works

**Comment by ScriptVortexDE** [comment]
only the api from whmcs works, not the connection to the api from freescout

**Comment by Lars-** [comment]
Then you probably are not using the correct credentials or the correct URL. I am sure it is not related to the module, but if you can share a screenshot of the settings, maybe I can see where it is wrong.

**Comment by ScriptVortexDE** [comment]
![image](https://github.com/user-attachments/assets/d9493f4d-3f15-47dd-87e4-61d9232d6839)

WHMCS is on https://dynlinq.net/c
And hats the url what i use

**Comment by Lars-** [comment]
If it’s on the same server, why don’t you use 127.0.0.1? How is ticket.dynlinq.net whitelisted in WHMCS?

**Comment by Lars-** [comment]
Also, try adding a trailing slash to the URL. I don’t know for sure if that is the problem, but it should be quick to try.
